config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  devise_for :users
  root 'splash#index'

  resources :categories
  resources :deals
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Deal, author: user
    can :manage, Category, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :icon, presence: true

  belongs_to :user
  has_and_belongs_to_many :deals

  def total_amount
    deals.sum('amount')
  end
end

app/models/deal.rb
class Deal < ApplicationRecord
  validates :name, :amount, :categories, presence: true, length: { maximum: 100 }
  validates :amount, numericality: { greater_than: 0 }

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true, length: { maximum: 100 }
  validates :email, uniqueness: true

  has_many :deals
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show]

  def index
    @categories = current_user.categories
  end

  def show
    @deals = @category.deals.order(created_at: 'desc')
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully deleted.' }
    end
  end

  private

  def set_category
    @category = Category.includes(:deals).find(params[:id])
  end

  def category_params
    params.fetch(:category, {}).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  load_and_authorize_resource

  def index
    redirect_to categories_url
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.author = current_user

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal.categories.first, notice: 'Transaction was successfully added.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def deal_params
    params.fetch(:deal, {}).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/categories/_category.html.erb
<%= link_to category_url(category) do %>
<div class="is-flex has-background-color-white mx-2 mt-1 p-2 card-shadow">
	<%= image_tag(category.icon, class: "image") %>
	<div class="is-flex flex-grow-1 flex-direction-column pl-2">
		<div class="is-flex justify-space-between my-2">
			<h5 class="fw-regular is-flex flex-grow-1"><%= category.name %></h5>
			<small class="fw-bold">$<%= category.total_amount %></small>
		</div>
		<small><%= category.created_at.strftime("%d %b %Y") %></small>
	</div>
</div>
<% end %>

app/views/categories/_form.html.erb
<div class="has-background-color is-flex flex-grow-1 flex-direction-column">
  <%= form_with(model: category) do |form| %>
    <div class="header">
      <%= render "shared/back_button" %>
      <div class="is-flex flex-grow-1 justify-content-center">
        <h2 class="title">New Category</h2>
      </div>
      <%= form.submit "Save", class: "button has-text-white" %>
    </div>
    <%= render "devise/shared/error_messages", resource: category %>
    <div class="input-group my-2 shadow-box">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "input", required: true %>
      <div class="divider"></div>
      <%= form.url_field :icon, placeholder: "Icon", class: "input", required: true %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="is-flex flex-direction-column flex-grow-1 has-background-color">
  <header class="header">
    <%= link_to root_path, class: 'button has-text-white' do %>
      <span class="material-icons-outlined">home</span>
    <% end %>
    <div class="is-flex flex-grow-1 justify-content-center">
      <h1 class="title">Categories</h1>
    </div>
    <%= button_to destroy_user_session_url, method: :delete, class: 'button has-text-white' do %>
      <span class="material-icons-outlined">logout</span>
    <% end %>
  </header>
  <%= render @categories %>
</div>
<footer class="p-4 is-secondary">
  <%= link_to 'Add a new category', new_category_path, class: "button is-outlined" %>
</footer>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="is-flex flex-direction-column flex-grow-1">
  <header class="header">
		<%= link_to categories_path, class: "button" do %>
      <span class="material-icons-outlined">arrow_back</span>
    <% end %>
    <div class="is-flex flex-grow-1 justify-content-center">
      <h1 class="title">Transactions</h1>
    </div>
    <%= link_to @category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button has-text-white' do %>
      <span class="material-icons-outlined">delete</span>
    <% end %>
  </header>
	<div class="p-4 is-flex justify-content-between">
		<p>Total Amount:</p>
		<p class="fw-bold">$<%= @category.total_amount.round(2) %></p>
	</div>
	<div class="divider mb-2"></div>
	<%= render 'deals/index', locals: { deals: @deals } %>
</div>
<footer class="p-4 is-secondary">
  <%= link_to 'Add a new transaction', new_deal_path, class: "button is-outlined" %>
</footer>

app/views/deals/_deal.html.erb
<div class="is-flex has-background-color-white mx-2 mt-1 p-2 card-shadow">
	<div class="is-flex flex-grow-1 flex-direction-column pl-2">
		<div class="is-flex justify-space-between my-2">
			<h5 class="fw-regular is-flex flex-grow-1"><%= deal.name %></h5>
			<small class="fw-bold">$<%= deal.amount.round(2) %></small>
		</div>
		<small><%= deal.created_at.strftime("%d %b %Y") %></small>
	</div>
</div>

app/views/deals/_form.html.erb
<div class="has-background-color is-flex flex-grow-1 flex-direction-column">
  <%= form_with(model: deal) do |form| %>
    <div class="header">
      <%= render "shared/back_button" %>
      <div class="is-flex flex-grow-1 justify-content-center">
        <h2 class="title">New Transaction</h2>
      </div>
      <%= form.submit "Save", class: "button has-text-white" %>
    </div>
    <%= render "devise/shared/error_messages", resource: deal %>
    <div class="input-group my-2 shadow-box">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "input", required: true %>
      <div class="divider"></div>
      <%= form.number_field :amount, placeholder: "Amount", class: "input", required: true %>
      <div class="divider"></div>
      <%= form.collection_select :category_ids, current_user.categories.order(:name), :id, :name, {}, { class: "input", multiple: true } %>
    </div>
  <% end %>
</div>

app/views/deals/_index.html.erb
<%= render @deals %>

app/views/deals/new.html.erb
<%= render 'form', deal: @deal %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayEasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
      rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="is-flex flex-grow-1 flex-direction-column">
      <%= yield %>
    </div>
    <% if notice.present? %>
      <div class="has-background-color-dark">
        <p class="notice p-4 fw-regular"><%= notice %></p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="has-background-color-dark">
        <p class="alert p-4 fw-regular"><%= alert %></p>
      </div>
    <% end %>
  </body>
</html>

app/views/shared/_back_button.html.erb
<%= link_to url_for(:back), class: 'button has-text-white' do %>
	<span class="material-icons-outlined">arrow_back</span>
<% end %>

app/views/splash/index.html.erb
<div class="container">
  <div class="is-flex flex-grow-1 justify-content-center align-items-center">
    <h1 class="fw-thin">PayEasy</h1>
  </div>
  <div class="is-flex flex-direction-column buttons">
    <%= link_to 'Log in', new_user_session_url, class: "button is-primary" %>
    <%= link_to 'Sign up', new_user_registration_url, class: "button" %>
  </div>
</div>